services:
  docker-coredns-sync:
    image: ghcr.io/stevenc4/docker-coredns-sync:latest
    container_name: docker-coredns-sync
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
