name: Publish Docker image

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.2.3

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: docker-coredns-sync

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set lowercase repo owner
        id: repo
        run: echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> "$GITHUB_OUTPUT"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ steps.repo.outputs.owner_lc }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: extract_version
        run: |
          version=${GITHUB_REF#refs/tags/v}
          major=$(echo "$version" | cut -d. -f1)
          minor=$(echo "$version" | cut -d. -f2)
          echo "version=$version" >> "$GITHUB_OUTPUT"
          echo "major=$major" >> "$GITHUB_OUTPUT"
          echo "minor=$minor" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm6
          tags: |
            ${{ env.REGISTRY }}/${{ steps.repo.outputs.owner_lc }}/${{ env.IMAGE_NAME }}:${{ steps.extract_version.outputs.version }}
            ${{ env.REGISTRY }}/${{ steps.repo.outputs.owner_lc }}/${{ env.IMAGE_NAME }}:${{ steps.extract_version.outputs.major }}.${{ steps.extract_version.outputs.minor }}
            ${{ env.REGISTRY }}/${{ steps.repo.outputs.owner_lc }}/${{ env.IMAGE_NAME }}:${{ steps.extract_version.outputs.major }}
            ${{ env.REGISTRY }}/${{ steps.repo.outputs.owner_lc }}/${{ env.IMAGE_NAME }}:latest